// Auto-generated by tools/build-kush-light-v2.mjs
// Neutral placeholder data so the kush-light layout has visible content
// without referencing the original brand. Replace with real data per client.

const placeholderImg = (label) =>
  'data:image/svg+xml;utf8,' + encodeURIComponent(
    '<svg xmlns="http://www.w3.org/2000/svg" width="600" height="600" viewBox="0 0 600 600">' +
    '<rect width="600" height="600" fill="#e5e7eb"/>' +
    '<text x="50%" y="50%" font-family="system-ui,sans-serif" font-size="28" fill="#9ca3af" text-anchor="middle" dominant-baseline="central">' + label + '</text>' +
    '</svg>'
  )

export const PLACEHOLDER_PRODUCTS = Array.from({ length: 12 }, (_, i) => {
  const n = i + 1
  const categories = ['Category A', 'Category B', 'Category C', 'Category D']
  return {
    id: String(n),
    name: 'Product ' + String(n).padStart(2, '0'),
    category: categories[i % categories.length],
    price: 19.99 + i * 5,
    description: 'Replace this description with real product details.',
    imageUrl: placeholderImg('Product ' + n),
    image: placeholderImg('Product ' + n),
    images: [placeholderImg('Product ' + n)],
    inStock: true,
    featured: i < 4,
    vendor: 'Brand Name',
    tags: [],
    specs: {},
  }
})

export const PLACEHOLDER_BLOG_POSTS = Array.from({ length: 6 }, (_, i) => {
  const n = i + 1
  return {
    id: String(n),
    title: 'Sample Post ' + n,
    slug: 'sample-post-' + n,
    excerpt: 'Replace this excerpt with the actual post summary text.',
    content: 'Replace this content with the actual blog post body. Multiple paragraphs supported.',
    imageUrl: placeholderImg('Post ' + n),
    author: 'Author Name',
    publishedAt: Date.now() - n * 86400000,
    createdAt: Date.now() - n * 86400000,
    tags: ['Sample'],
    readTime: 4 + i,
  }
})

export const PLACEHOLDER_HOMEPAGE = {
  hero: {
    title: 'Brand Name',
    subtitle: 'Tagline goes here — describe what makes the brand different in one short sentence.',
    ctaPrimary: 'Get Started',
    ctaSecondary: 'Learn More',
    imageUrl: placeholderImg('Hero'),
  },
  sections: [
    { id: 'hero', enabled: true, title: 'Brand Name' },
    { id: 'about', enabled: true, title: 'About Us', body: 'Replace this with your story — two or three sentences about who you are and what you offer.' },
    { id: 'products', enabled: true, title: 'Featured Items' },
    { id: 'blog', enabled: true, title: 'From the Journal' },
    { id: 'contact', enabled: true, title: 'Get In Touch' },
  ],
  banners: [
    { id: 1, title: 'Banner Headline', subtitle: 'Banner sub-headline.', imageUrl: placeholderImg('Banner'), link: '#' },
  ],
}

export const PLACEHOLDER_LOGOS = Array.from({ length: 8 }, (_, i) => ({
  id: String(i + 1),
  name: 'Partner ' + (i + 1),
  imageUrl: placeholderImg('Logo ' + (i + 1)),
  url: '#',
}))

export const PLACEHOLDER_MUSIC = Array.from({ length: 6 }, (_, i) => ({
  id: String(i + 1),
  title: 'Track ' + (i + 1),
  artist: 'Artist Name',
  album: 'Sample Album',
  duration: 180 + i * 20,
  imageUrl: placeholderImg('Track ' + (i + 1)),
  url: '#',
}))

// Path-keyed fixture map used by the firebase/database stub. When a kush component
// does ref(db, 'blogPosts') the stub returns PLACEHOLDER_FIXTURES.blogPosts.
export const PLACEHOLDER_FIXTURES = {
  products: PLACEHOLDER_PRODUCTS,
  enhancedProducts: PLACEHOLDER_PRODUCTS,
  blogPosts: PLACEHOLDER_BLOG_POSTS,
  posts: PLACEHOLDER_BLOG_POSTS,
  blog: PLACEHOLDER_BLOG_POSTS,
  homepage: PLACEHOLDER_HOMEPAGE,
  homepageContent: PLACEHOLDER_HOMEPAGE,
  pageContent: PLACEHOLDER_HOMEPAGE,
  logos: PLACEHOLDER_LOGOS,
  partners: PLACEHOLDER_LOGOS,
  brands: PLACEHOLDER_LOGOS,
  music: PLACEHOLDER_MUSIC,
  tracks: PLACEHOLDER_MUSIC,
}
