// Auto-generated by tools/build-kush-light-v2.mjs
// Replaces <img> and <video> from the original kush repo with a flat grey box.

export default function MediaPlaceholder({ kind = 'image', width, height, className, style, alt, ...rest }) {
  const inferredAR = (width && height) ? `${width} / ${height}` : '16 / 9'
  return (
    <div
      role="img"
      aria-label={alt || `Placeholder ${kind}`}
      className={className}
      style={{
        width: width ? (typeof width === 'number' ? width + 'px' : width) : '100%',
        height: height ? (typeof height === 'number' ? height + 'px' : height) : 'auto',
        aspectRatio: (!width || !height) ? '16 / 9' : inferredAR,
        background: '#e5e7eb',
        color: '#9ca3af',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: 13,
        fontFamily: 'system-ui, -apple-system, sans-serif',
        letterSpacing: 0.5,
        textTransform: 'uppercase',
        borderRadius: 6,
        ...style,
      }}
      {...rest}
    >
      [{kind}]
    </div>
  )
}
